version: "3.7"

services:
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=docker
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo-data:/data/db
      - ./volumes/mongo-data/collections:/docker-entrypoint-initdb.d

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass docker
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis-data:/var/lib/redis
